### ISSUE TITLE
PyPi version out of date

### ISSUE THREAD

**Issue by aklaver** [18F/rdbms-subsetter#16]
I was trying this out and did:

pip install rdbms-subsetter

into a Python 2.7 virtualenv.

Running that version resulted in an issue with the Y/n confirmation. I then downloaded the zip version from here and installed it. The zip version has the Python 2.x input fix and the confirmation works.

**Comment by catherinedevlin** [comment]
Fixed with the 0.2.3 release.  Thanks!
