### ISSUE TITLE
Unable to make subset of a PostgreSQL db with ARRAY columns

### ISSUE THREAD

**Issue by fbertola** [18F/rdbms-subsetter#22]
When I try to make a subset of a _PostgreSQL_ db with _ARRAY_ columns, `rdbms-subsetter` fails with this error:

```
column <column> is of type <type>[] but expression is of type text[]
```

Is there a way to force casting to the right type?

**Comment by fbertola** [comment]
After further investigation, I found that the problem was with `ARRAY[ENUM]` columns. This is a [known problem](https://bitbucket.org/zzzeek/sqlalchemy/issues/3467/array-of-enums-does-not-allow-assigning). The proposed PR fixes that (albeit being a little bit of a hack :sweat_smile:).

**Comment by catherinedevlin** [comment]
Got your fix merged!  Thank you!  It will be in the next release.
